# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

target 'YCDouYuZB' do


pod 'Alamofire'

  # Pods for YCDouYuZB

  target 'YCDouYuZBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YCDouYuZBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
